CREATE TABLE IF NOT EXISTS users
(
    id         BIGSERIAL    PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    email      VARCHAR(150) NOT NULL UNIQUE,
    age        INTEGER,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);